#!/usr/bin/env python3
"""
为 cgns_test_lib 转换后的 10 个用例（01-10）生成完整可执行的 OpenFOAM 算例文件。
在 build 目录下，out_01_single_zone_tetra ... out_10_fan_rotor_stator 已含 constant/polyMesh，
本脚本补充 system/、0/、constant/ 中其余文件，使每个目录可直接运行 simpleFoam。

用法（在项目根目录）:
  python3 cgns_test_lib/scripts/create_openfoam_cases.py [build_dir]
  build_dir 默认为 ./build
"""

import re
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT = SCRIPT_DIR.parent.parent
BUILD_DIR = Path(sys.argv[1]) if len(sys.argv) > 1 else REPO_ROOT / "build"

# 01-10 的用例输出目录名（与 run_all_conversions.sh 一致）
CASE_DIRS = [
    "out_01_single_zone_tetra",
    "out_02_single_zone_hex",
    "out_03_external_flow_3d",
    "out_04_pipe_flow",
    "out_05_duct_flow",
    "out_06_electronics_solid",
    "out_07_electronics_fluid_solid",
    "out_08_heat_sink",
    "out_09_two_zone_interface",
    "out_10_fan_rotor_stator",
]


def parse_boundary(case_path: Path):
    """解析 constant/polyMesh/boundary，返回 [(patch_name, type), ...]"""
    boundary_file = case_path / "constant" / "polyMesh" / "boundary"
    if not boundary_file.exists():
        return []
    text = boundary_file.read_text()
    # 匹配 patch 名称和 type（patch/wall/cyclicAMI/...）
    patches = re.findall(r"(\w+)\s*\{\s*type\s+(\w+)\s*;", text)
    return patches


def write_foam_header(obj, cls, fmt="ascii"):
    return f"""/*--------------------------------*- C++ -*----------------------------------*\\
|  Generated by cgns_test_lib/scripts/create_openfoam_cases.py          |
\\*---------------------------------------------------------------------------*/
FoamFile
{{
    version     2.0;
    format      {fmt};
    class       {cls};
    object      {obj};
}}
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

"""


def boundary_field_u(patches):
    lines = ["boundaryField\n{"]
    for name, btype in patches:
        if btype == "cyclicAMI":
            lines.append(f"""    {name}
    {{
        type            cyclicAMI;
        value           $internalField;
    }}
""")
        else:
            lines.append(f"""    {name}
    {{
        type            noSlip;
    }}
""")
    lines.append("}\n\n// ************************************************************************* //")
    return "\n".join(lines)


def boundary_field_p(patches):
    lines = ["boundaryField\n{"]
    for name, btype in patches:
        if btype == "cyclicAMI":
            lines.append(f"""    {name}
    {{
        type            cyclicAMI;
        value           $internalField;
    }}
""")
        else:
            lines.append(f"""    {name}
    {{
        type            zeroGradient;
    }}
""")
    lines.append("}\n\n// ************************************************************************* //")
    return "\n".join(lines)


def boundary_field_nut(patches):
    lines = ["boundaryField\n{"]
    for name, btype in patches:
        lines.append(f"""    {name}
    {{
        type            nutkWallFunction;
        value           uniform 0;
    }}
""")
    lines.append("}\n\n// ************************************************************************* //")
    return "\n".join(lines)


def boundary_field_nuTilda(patches):
    lines = ["boundaryField\n{"]
    for name, btype in patches:
        lines.append(f"""    {name}
    {{
        type            fixedValue;
        value           uniform 0;
    }}
""")
    lines.append("}\n\n// ************************************************************************* //")
    return "\n".join(lines)


def ensure_wall_boundary(case_path: Path, patches: list):
    """将 noSlip 使用的 patch 在 polyMesh/boundary 中改为 type wall，以便 nutWallFunction 使用。"""
    boundary_file = case_path / "constant" / "polyMesh" / "boundary"
    text = boundary_file.read_text(encoding="utf-8")
    # 对非 cyclicAMI 的 patch 将 type patch 改为 type wall
    for name, btype in patches:
        if btype != "cyclicAMI":
            text = re.sub(
                rf"({re.escape(name)}\s*\{{\s*type\s+)patch(\s*;)",
                r"\g<1>wall\2",
                text,
            )
    boundary_file.write_text(text, encoding="utf-8")


def create_case(case_path: Path, patches: list) -> bool:
    case_path = case_path.resolve()
    if not (case_path / "constant" / "polyMesh" / "boundary").exists():
        return False

    ensure_wall_boundary(case_path, patches)

    # system/controlDict
    (case_path / "system").mkdir(exist_ok=True)
    (case_path / "system").mkdir(exist_ok=True)
    (case_path / "0").mkdir(exist_ok=True)
    (case_path / "constant").mkdir(exist_ok=True)

    (case_path / "system" / "controlDict").write_text(write_foam_header("controlDict", "dictionary") + """
application     simpleFoam;

startFrom       startTime;
startTime       0;
stopAt          endTime;
endTime         10;
deltaT          1;
writeControl    runTime;
writeInterval  5;
purgeWrite      2;
writeFormat     ascii;
writePrecision  6;
runTimeModifiable true;
// ************************************************************************* //
""", encoding="utf-8")

    (case_path / "system" / "fvSchemes").write_text(write_foam_header("fvSchemes", "dictionary") + """
ddtSchemes
{
    default         steadyState;
}

gradSchemes
{
    default         Gauss linear;
}

divSchemes
{
    default         none;
    div(phi,U)      bounded Gauss linearUpwind grad(U);
    div((nuEff*dev2(T(grad(U))))) Gauss linear;
}

laplacianSchemes
{
    default         Gauss linear corrected;
}

interpolationSchemes
{
    default         linear;
}

snGradSchemes
{
    default         corrected;
}
// ************************************************************************* //
""", encoding="utf-8")

    (case_path / "system" / "fvSolution").write_text(write_foam_header("fvSolution", "dictionary") + """
solvers
{
    p
    {
        solver          GAMG;
        tolerance       1e-06;
        relTol          0.01;
    }

    U
    {
        solver          smoothSolver;
        smoother        symGaussSeidel;
        tolerance       1e-05;
        relTol          0.1;
    }
}

SIMPLE
{
    nNonOrthogonalCorrectors 0;
    pRefCell        0;
    pRefValue       0;
    residualControl
    {
        p               1e-4;
        U                1e-4;
    }
}
// ************************************************************************* //
""", encoding="utf-8")

    # 0/U
    (case_path / "0" / "U").write_text(
        write_foam_header("U", "volVectorField")
        + "dimensions      [0 1 -1 0 0 0 0];\n\ninternalField   uniform (0 0 0);\n\n"
        + boundary_field_u(patches),
        encoding="utf-8",
    )

    # 0/p
    (case_path / "0" / "p").write_text(
        write_foam_header("p", "volScalarField")
        + "dimensions      [0 2 -2 0 0 0 0];\n\ninternalField   uniform 0;\n\n"
        + boundary_field_p(patches),
        encoding="utf-8",
    )

    # constant/transportProperties
    (case_path / "constant" / "transportProperties").write_text(write_foam_header("transportProperties", "dictionary") + """
transportModel  Newtonian;
nu              nu [ 0 2 -1 0 0 0 0 ] 1e-05;
// ************************************************************************* //
""", encoding="utf-8")

    # constant/turbulenceProperties (laminar for robust run)
    (case_path / "constant" / "turbulenceProperties").write_text(write_foam_header("turbulenceProperties", "dictionary") + """
simulationType  laminar;
// ************************************************************************* //
""", encoding="utf-8")

    # Remove nut/nuTilda if present (laminar case)
    for f in ("nut", "nuTilda"):
        (case_path / "0" / f).unlink(missing_ok=True)

    # Allrun (source OpenFOAM if OPENFOAM_BASHRC set, else assume env loaded)
    (case_path / "Allrun").write_text("""#!/bin/bash
cd "${0%/*}" || exit 1
[ -n "${OPENFOAM_BASHRC}" ] && source "${OPENFOAM_BASHRC}"
simpleFoam
""", encoding="utf-8")
    (case_path / "Allrun").chmod(0o755)

    return True


def main():
    build = BUILD_DIR.resolve()
    if not build.is_dir():
        print(f"Build directory not found: {build}", file=sys.stderr)
        sys.exit(1)

    ok = 0
    for name in CASE_DIRS:
        case_path = build / name
        if not case_path.is_dir():
            print(f"Skip {name}: not found")
            continue
        patches = parse_boundary(case_path)
        if not patches:
            print(f"Skip {name}: no boundary or polyMesh missing")
            continue
        if create_case(case_path, patches):
            print(f"OK  {name}")
            ok += 1
        else:
            print(f"Fail {name}")
    print(f"\nDone: {ok}/{len(CASE_DIRS)} cases created. Run from build: cd out_01_single_zone_tetra && ./Allrun")
    sys.exit(0 if ok == len(CASE_DIRS) else 1)


if __name__ == "__main__":
    main()
